# Generated by Django 5.2.7 on 2025-11-04 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('min_people', models.IntegerField()),
                ('max_people', models.IntegerField()),
                ('transportation', models.CharField(choices=[('public', 'Public Transportation'), ('private', 'Private Transportation'), ('walk', 'Walking')], max_length=20)),
                ('meeting_location', models.CharField(choices=[('mine', 'My Place'), ('yours', 'Your Place'), ('first', 'First place')], max_length=20)),
                ('price', models.IntegerField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('rating', models.IntegerField(default=0)),
                ('rates', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tour_images/')),
                ('isthumbnail', models.BooleanField(default=False)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_images', to='Tour.tour')),
            ],
        ),
        migrations.CreateModel(
            name='TourPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tour.place')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tour.tour')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('tour', 'place')},
            },
        ),
        migrations.AddField(
            model_name='tour',
            name='places',
            field=models.ManyToManyField(blank=True, related_name='tours', through='Tour.TourPlace', through_fields=('tour', 'place'), to='Tour.place'),
        ),
    ]
