# Generated by Django 5.2.7 on 2025-11-14 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0001_initial'),
        ('Tour', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='rates',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='rating',
        ),
        migrations.AddField(
            model_name='tour',
            name='guide',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='Profiles.guide'),
        ),
        migrations.AddField(
            model_name='tour',
            name='rating_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of ratings received'),
        ),
        migrations.AddField(
            model_name='tour',
            name='rating_total',
            field=models.PositiveIntegerField(default=0, help_text='Sum of all ratings'),
        ),
        migrations.CreateModel(
            name='TourRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('review', models.TextField(blank=True, max_length=1000, null=True)),
                ('review_tags', models.JSONField(blank=True, default=list, help_text="JSON array of tags describing this review, e.g., ['Family-friendly', 'Adventure']")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='Tour.tour')),
                ('tourist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour_ratings', to='Profiles.tourist')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('tourist', 'tour')},
            },
        ),
        migrations.CreateModel(
            name='TourRatingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tour_rating_images/')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Tour.tourrating')),
            ],
        ),
    ]
