# Generated by Django 5.2.7 on 2025-11-05 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourplace',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_places', to='Tour.tour'),
        ),
    ]
